[air]
Cp = 1006                               # Specific heat capacity at constant pressure [J/kg/K]
MolarMass = 0.02897                     # Molar weight [kg/mol]
k = 1.4                                 # Ratio of specific heats, cp/cv [-]
viscosity = 1.788e-5                    # Dynamic viscosity [Pa s]

[h2]
Cp = 14403                              # Specific heat at constant pressure [J/kg/K]                                       
MolarMass = 0.00201568                  # Molar weight [kg/mol] 
k = 1.41                                # Ratio of specific heats, cp/cv [-]
viscosity = 0.88e-5                     # Dynamic viscosity [Pa s]

[R134a]
Cp = 821                                # Specific heat capacity at constant pressure [J/kg/K]
MolarMass = 0.10203                     # Molar weight [kg/mol]
k = 1.13                                # Ratio of specific heats, cp/cv [-]
viscosity = 1.08e-5                     # Dynamic viscosity [Pa s]
