[project]
name = "h2iCompressor"
version = "1.0.0"
description = "A python code for predicting centrifugal compressor performance"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
  "marimo>=0.8.22",
  "matplotlib",
  "numpy",
  "pandas",
  "toml",
]
