[fluid_properties]
Cp = 1006                                   # Cp air [J/kg/K], 
MolarMass = 0.02897                         # Molecular weight of air [kg/mol].   
k = 1.4                                    # Basicly similar for air and hydrogen
viscosity = 1.788e-5                        # Air viscosity based on total conditions MSG: Should be dynamic viscosity. This is may be wrong value
R_uni = 8.314                               # Universal gas constant [J/mol/K]