[fluid_properties]
Cp = 1006                                   # Cp air [J/kg/K], 
MolarMass = 0.02897                         # Molecular weight of air [kg/mol].   
k = 1.41                                    # Basicly similar for air and hydrogen
viscosity = 1.778e-5                        # Air viscosity based on total conditions
R_uni = 8.314                               # Universal gas constant [J/mol/K]