[impeller_properties]
# Ti-6Al-2Sn-4Zr-2Mo titanium  properties https://www.azom.com/article.aspx?ArticleID=9298
impellerDensity = 1540                          # Impeller density [kg/m3]
impellerTensileStrength = 9e8                   # Approximate ultimate tensile strength UTS [Pa]

# Impeller exit flow parameters
lambda2 = 2                                     # Exit swirl parameter                                         
etaStage = 0.72                                  # Isentropic Stage efficiency [-]. Used for iteration     


[diffuser_properties]
# Diffuser parameters
etad = 0.85                                     # Diffuser efficiency
AR = 2.5                                        # Inlet/outlet area ratio of the diffuser [-]         


[off_design_parameters_unknown]
No = 1.0                                        # Off design speed percentage that requires performance prediction [rpm]
tu = 0.002                                      # Blade thickness [m]
curvet1 = 0                                     # Inducer inlet tip wall curvature [m^-1]
curveh1 = 0                                     # Inducer inlet hub wall curvature [m^-1]
x = 10                                          # Streamline angle [degrees] from axial direction
kBL = 0.6                                       # Blading loss coefficient [-]
kSF = 7.0                                       # Skin friction coefficient [-]
Cf = 0.01                                       # Friction coefficient [-]
    

[iteration_parameters]
# Iteration control
etaLowerLimit = 0                               # Lowest efficiency allowed
etaUpperLimit = 0.999                             # Highest efficiency allowed
bladeVelUpperLimit = 1200                       # Highest blade velocity allowed
bladeVelLowerLimit = 0                          # Lowest blade velocity allowed 
beta2Bmax = - 50                                # "Maximum" beta iterated over
beta2Bmin = 0                                   # "Minimum" beta iterated over  
bladeMin = 2                                    # Lowest bladenumber allowed
bladeMax = 30                                   # Highest bladenumber allowed
iterTol = 0.01                                  # Loop tolerance condition for pressure ratio


[parameters_to_vary]
# VARY THESE PARAMETERS
Pr = 1.625                                        # Pressure ratio [-]
N0 = 120000                                     # Rotational speed
rh = 0.00575                                    # In case we use geometry_2
r1 = 0.0186                                     # In case we use geometry_2
r2 = 0.024                                      # In case we use geometry_2

#rhDivr1 = 0.5313                               # Inducer hub radius over inducer tip radius
#r1Divr2 = 0.5614                               # Inducer tip radius over impeller exit diameter. rt1 divided by rt2 ,making rt2 increase through array progression


[off_design_parameters]
bladeAngle = - 40                             # Blade angle of interest for off-desing_performance.py [degrees]
bladeNumber = 12                                # Blade number of interest for off-desing_performance.py