# Compressor at LUT, Finland described in https://doi.org/10.1155/2019/7415263 (in this paper the diameter is wrongly interchanged with radius)


[impeller_properties]
# Ti-6Al-2Sn-4Zr-2Mo titanium  properties https://www.azom.com/article.aspx?ArticleID=9298
impellerDensity = 1540                          # Impeller density [kg/m3]
impellerTensileStrength = 9e8                   # Approximate ultimate tensile strength UTS [Pa]

# Impeller exit flow parameters
lambda2 = 2.25                                  # Exit swirl parameter                                         
etaStage = 0.8                                  # Isentropic Stage efficiency [-]. Used for iteration  
eta_rotor = 0.90                                # Rotor efficiency [-]


[diffuser_properties]
# Diffuser parameters
etad = 0.85                                     # Diffuser efficiency. MSG: Not defined by Galvas 
AR = 1.69                                       # Inlet/outlet area ratio of the (vaneless) diffuser [-]  


[off_design_parameters_unknown]
No = 1.0                                        # Off design speed percentage that requires performance prediction [rpm]
tu = 0.003                                      # Blade thickness [m]
curvet1 = 0                                     # Inducer inlet tip wall curvature [m^-1]
curveh1 = 7                                     # Inducer inlet hub wall curvature [m^-1]
x = 0                                           # Streamline angle [degrees] from axial direction
kBL = 0.6                                       # Blading loss coefficient [-]
kSF = 7.0                                       # Skin friction coefficient [-]
Cf = 0.006                                      # Friction coefficient [-]
    

[iteration_parameters]
# Iteration control
etaLowerLimit = 0                               # Lowest efficiency allowed
etaUpperLimit = 0.9999                          # Highest efficiency allowed
bladeVelUpperLimit = 1200                       # Highest blade velocity allowed
bladeVelLowerLimit = 0                          # Lowest blade velocity allowed 
beta2Bmax = - 40                                # "Maximum" beta iterated over
beta2Bmin = - 1                                 # "Minimum" beta iterated over  
bladeMin = 2                                    # Lowest bladenumber allowed
bladeMax = 20                                   # Highest bladenumber allowed


[parameters_to_vary]
# VARY THESE PARAMETERS
Pr = 2.2                                       # Pressure ratio [-]
Ndes = 27720                                   # Rotational speed
rhDivr1 = 0.3002                               # Radius ratio
#rh = 0.02025                                  # Hub radius [m], r1 = 0.06745, r2 = 0.13545


[off_design_parameters]
bladeAngle = - 40                               # Blade angle of interest for off-desing_performance.py [degrees]
bladeNumber = 18                                # Blade number of interest for off-desing_performance.py
N_off_design_arr = [28920,                      # Rotational speeds for predicting off-design performance [rpm]
                    27720,
                    24960,
                    21840,
                    19380]
V0DivVcr_off_design_arr = [0.02, 0.55,          # Critical velocity ranges for predicting off-design performance [-]
                           0.02, 0.52,
                           0.02, 0.46,
                           0.02, 0.41,
                           0.02, 0.37]