[impeller_properties]
# Ti-6Al-2Sn-4Zr-2Mo titanium  properties https://www.azom.com/article.aspx?ArticleID=9298
impellerDensity = 1540                          # Impeller density [kg/m3]
impellerTensileStrength = 12e8#9e8              # Approximate ultimate tensile strength UTS [Pa]

# Impeller exit flow parameters
lambda2 = 2                                     # Exit swirl parameter                                         
etaStage = 0.6                                  # Isentropic Stage efficiency [-]. Used for iteration     
eta_rotor = 0.9                                 # Rotor efficiency [-]


[diffuser_properties]
# Diffuser parameters
etad = 0.85                                     # Diffuser efficiency. MSG: Not defined by Galvas 
AR = 2.75                                       # Inlet/outlet area ratio of the diffuser [-] MSG: AR in Galvas is the vaned diffuser area ratio. However, we assume a vaneless diffuser? So wrong?     


[off_design_parameters_unknown]
No = 1.0                                        # Off design speed percentage that requires performance prediction [rpm]
tu = 0.002                                      # Blade thickness [m]
curvet1 = 0                                     # Inducer inlet tip wall curvature [m^-1]
curveh1 = 7                                     # Inducer inlet hub wall curvature [m^-1]
x = 0                                           # Streamline angle [degrees] from axial direction
kBL = 0.6                                       # Blading loss coefficient [-]
kSF = 7.0                                       # Skin friction coefficient [-]
Cf = 0.004                                      # Friction coefficient [-]
    

[iteration_parameters]
# Iteration control
beta2Bmax = - 25                                # Maximum blade angle
beta2Bmin = -20                                 # Minimum blade angle
bladeMin = 30                                   # Lowest bladenumber allowed
bladeMax = 35                                   # Highest bladenumber allowed


[parameters_to_vary]
# VARY THESE PARAMETERS
Pr = 6.5                                        # Pressure ratio [-]
Ndes = 72000                                    # Rotational speed
rhDivr1 = 0.5313                                # Radius ratio [-], r1Divr2 = 0.5614


[off_design_parameters]
bladeAngle = - 25                               # Blade angle of interest for off-desing_performance.py [degrees]
bladeNumber = 32                                # Blade number of interest for off-desing_performance.py
N_off_design_arr = [72000]                      # Rotational speeds for predicting off-design performance [rpm]
V0DivVcr_off_design_arr = [0.1, 0.51]            # Critical velocity ranges for predicting off-design performance [-]
constant_eff_lines = [0.71, 0.73, 0.75, 0.77, 0.78, 0.81]    # Lines of constant efficiency in compressor performance map