[impeller_properties]
# Ti-6Al-2Sn-4Zr-2Mo titanium  properties https://www.azom.com/article.aspx?ArticleID=9298
impellerDensity = 1540                          # Impeller density [kg/m3]
impellerTensileStrength = 9e8                   # Approximate ultimate tensile strength UTS [Pa]

# Impeller exit flow parameters
lambda2 = 2                                     # Exit swirl parameter                                         
etaStage = 0.6                                  # Isentropic Stage efficiency [-]. Used for iteration     
eta_rotor = 0.9                                 # Rotor efficiency [-]


[diffuser_properties]
# Diffuser parameters
etad = 0.85                                     # Diffuser efficiency (-)
AR = 2.5                                        # Inlet/outlet area ratio of the diffuser [-]         


[off_design_parameters_unknown]
No = 1.0                                        # Off design speed percentage that requires performance prediction [rpm]
tu = 0.002                                      # Blade thickness [m]
curvet1 = 0                                     # Inducer inlet tip wall curvature [m^-1]
curveh1 = 0                                     # Inducer inlet hub wall curvature [m^-1]
x = 10                                          # Streamline angle [degrees] from axial direction
kBL = 0.6                                       # Blading loss coefficient [-]
kSF = 7.0                                       # Skin friction coefficient [-]
Cf = 0.01                                       # Friction coefficient [-]
    

[iteration_parameters]
# Iteration control
beta2Bmax = - 50                                # Maximum blade angle
beta2Bmin = 0                                   # Minimum blade angle
bladeMin = 2                                    # Lowest bladenumber allowed
bladeMax = 30                                   # Highest bladenumber allowed


[parameters_to_vary]
# VARY THESE PARAMETERS
Pr = 1.24                                       # Pressure ratio [-]
Ndes = 40000                                    # Rotational speed
rhDivr1 = 0.35                                  # Ratio commonly given


[off_design_parameters]
bladeAngle = - 35                               # Blade angle of interest for off-desing_performance.py [degrees]
bladeNumber = 30                                # Blade number of interest for off-desing_performance.py
N_off_design_arr = [40000]                      # Rotational speeds for predicting off-design performance [rpm]
V0DivVcr_off_design_arr = [0.1, 0.7]            # Critical velocity ranges for predicting off-design performance [-]
constant_eff_lines = [0.71, 0.73, 0.75, 0.77, 0.78, 0.81]    # Lines of constant efficiency in compressor performance map