[inlet_conditions]
mdot = 25                                   # Mass flow rate [kg/s] ((300 * 10 ** 3 ) / (60 ** 2)) / 6  
P00 = 3e6                                   # Inlet stagnation pressure [Pa]. Not the same as inlet pressure?
T00 = 293                                   # Inlet stagnation temperature [K]. Not the same as inlet temperature?
Cm1i_min = 10                               # Minimum inlet absolute meridional velocity [m/s]
Cm1i_max = 600.5                            # Maximal inlet absolute meridional velocity [m/s]
Cm1i_step = 1                               # Step length for inlet absolute meridional velocity [m/s]
alpha1 = 0                                  # Absolute inlet velocity angle [deg]
B1 = 0.04                                   # Boundary layer blockage [-],        substance viscocity dependant