# Compressor at LUT, Finland described in https://doi.org/10.1155/2019/7415263 (in this paper the diameter is wrongly interchanged with radius)


[inlet_conditions]
mdot = 1.8                                  # Mass flow rate [kg/s] at design point ((300 * 10 ** 3 ) / (60 ** 2)) / 6  
P00 = 96000                                 # Inlet stagnation pressure [Pa]. Not the same as inlet pressure?
T00 = 300                                   # Inlet stagnation temperature [K]. Not the same as inlet temperature?
Cm1i_min = 1                                # Minimum inlet absolute meridional velocity [m/s]      NOT IN USE, must be set in settings.py
Cm1i_max = 600.5                            # Maximal inlet absolute meridional velocity [m/s]     NOT IN USE, must be set in settings.py
Cm1i_step = 1                               # Step length for inlet absolute meridional velocity [m/s]  NOT IN USE, must be set in settings.py
alpha1 = 0                                  # Absolute inlet velocity angle [deg]
B1 = 0.04                                   # Boundary layer blockage [-],        substance viscocity dependant