# Compressor described in Japikse book


[inlet_conditions]
mdot = 9.435                                  # Mass flow rate [kg/s] at design point ((300 * 10 ** 3 ) / (60 ** 2)) / 6  
P00 = 304748.27                             # Inlet stagnation pressure [Pa]. Not the same as inlet pressure?
T00 = 277.594                               # Inlet stagnation temperature [K]. Not the same as inlet temperature?
Cm1i_min = 1                                # Minimum inlet absolute meridional velocity [m/s]      NOT IN USE, must be set in settings.py
Cm1i_max = 600.5                            # Maximal inlet absolute meridional velocity [m/s]     NOT IN USE, must be set in settings.py
Cm1i_step = 0.5                               # Step length for inlet absolute meridional velocity [m/s]  NOT IN USE, must be set in settings.py
alpha1 = 0                                  # Absolute inlet velocity angle [deg]
B1 = 0.02                                   # Boundary layer blockage [-],        substance viscocity dependant