# Compressor described in Japikse (1996)


[inlet_conditions]
mdot = 9.435                                # Mass flow rate at design point [kg/s]
P00 = 304748.27                             # Inlet stagnation pressure [Pa]
T00 = 277.594                               # Inlet stagnation temperature [K]
Cm1i_min = 1                                # Minimum inlet absolute meridional velocity [m/s] 
Cm1i_max = 600.5                            # Maximal inlet absolute meridional velocity [m/s] 
Cm1i_step = 0.5                             # Step length for inlet absolute meridional velocity [m/s]  
alpha1 = 0                                  # Absolute inlet velocity angle [deg]
B1 = 0.02                                   # Boundary layer blockage [-] (substance viscocity dependant)