# Compressor at LUT, Finland described in https://doi.org/10.1155/2019/7415263 (in this paper the diameter is wrongly interchanged with radius)


[inlet_conditions]
mdot = 1.8                                  # Mass flow rate at design point [kg/s]
P00 = 96000                                 # Inlet stagnation pressure [Pa]
T00 = 300                                   # Inlet stagnation temperature [K]
Cm1i_min = 1                                # Minimum inlet absolute meridional velocity [m/s]   
Cm1i_max = 600.5                            # Maximal inlet absolute meridional velocity [m/s]   
Cm1i_step = 1                               # Step length for inlet absolute meridional velocity [m/s]
alpha1 = 0                                  # Absolute inlet velocity angle [deg]
B1 = 0.04                                   # Boundary layer blockage [-] (substance viscocity dependant)